
-- Q1. What is the total revenue generated by male and female customers ?
select gender, sum(purchase_amount) as revenue
from my_table
group by gender; 

-- Q2. Which customer used a discount but still spent more than average purchase amount?
select customer_id , purchase_amount
from my_table
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from my_table);

-- Q3. Which are the top 5 product with the highest review rating?
select item_purchased, ROUND(avg(review_rating),2) AS 'Average product rating '
from my_table
group by item_purchased
order by avg (review_rating) desc
limit 5;

-- Q4. Compare the average purchase amount between Standard and Express shipping?
select shipping_type,
ROUND(avg(purchase_amount),2)
from my_table
where shipping_Type in ('Standard','Express')
group by shipping_type;

-- Q5. do subscribed customers spend more? 
-- Compare spend and total revenue between subscribers and non-subscribers?
select subscription_status , 
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from my_table
group by subscription_status
order by total_revenue, avg_spend desc;

-- Q6. Which 5 products have the Highest percentage of purchases with discounts applied?
select item_purchased,
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end) / count(*),2) as discount_rate
from my_table
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. Segment customers as New ,Returning, and loyal based on thier total 
-- number of previous purchases and show the count of each segment ?
with customer_type as (
select customer_id, previous_purchases,
case
	when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    END AS customer_segment
from my_table
)

select customer_segment, count(*) as 'No of Customers'
from customer_type
group by customer_segment;

-- what are the top 3 most purchased products in each category?
with item_counts as (
select category,item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id)desc) as item_rank
from my_table
group by category , item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <= 3;

-- Q9. Are customer who are repeat buyers (more than 5 purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as returning
from my_table
where previous_purchases > 5
group by subscription_status;


-- Q10.What is the revenue contribution by each age group?
select age_group ,  
sum(purchase_amount) as total_revenue
from my_table
group by age_group
order by total_revenue desc;